language: go
go:
  - 1.1.2
  - tip

script:
  - go build ./...
  - go fmt ./...
  - (go version | grep "version go1.1") || go get code.google.com/p/go.tools/cmd/vet
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
